package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// generateCode orchestrates the generation of enums and elements files.
// It calls specific functions to generate enumeration and struct files.
func generateCode() {
	generateEnumsFile()
	generateElementsFile()
}

// generateEnumsFile creates the enums.go file and populates it with all enums.
// It handles file creation and deferred closing.
func generateEnumsFile() {
	fEnums, err := os.Create(
		"spreadsheet/elements/enums.go",
	)
	if err != nil {
		panic(
			fmt.Errorf(
				"failed to create enums.go: %w",
				err,
			),
		)
	}
	defer func() {
		if errClose := fEnums.Close(); errClose != nil {
			fmt.Fprintf(
				os.Stderr,
				"failed to close enums file: %v\n",
				errClose,
			)
		}
	}()

	// revive:disable:line-length-limit // header contains long lint disabling list
	header := `//revive:disable:file-length-limit,max-public-structs,line-length-limit,comments-density // Generated code
//nolint
//
// Code generated by gen-go-spreadsheet. DO NOT EDIT.
package elements

import (
	"encoding/xml"
)

`
	// revive:enable:line-length-limit
	writeHeader(fEnums, header)

	for name := range enumMap {
		t := enumMap[name]
		generateEnum(fEnums, &t)
	}
}

// generateElementsFile creates the elements.go file and populates it.
// It reads schema definitions from the Open-XML-SDK data directory.
func generateElementsFile() {
	schemasDir := "Open-XML-SDK/data/schemas"
	files, err := os.ReadDir(schemasDir)
	if err != nil {
		panic(
			fmt.Errorf(
				"failed to read schemas dir: %w",
				err,
			),
		)
	}

	fElems, err := os.Create(
		"spreadsheet/elements/elements.go",
	)
	if err != nil {
		panic(
			fmt.Errorf(
				"failed to create elements.go: %w",
				err,
			),
		)
	}
	defer func() {
		if errClose := fElems.Close(); errClose != nil {
			msg := "failed to close elements file: %v\n"
			fmt.Fprintf(os.Stderr, msg, errClose)
		}
	}()

	// revive:disable:line-length-limit // header contains long lint disabling list
	header := `//revive:disable:file-length-limit,function-length,unchecked-type-assertion,line-length-limit,max-public-structs,cognitive-complexity,cyclomatic,comments-density // Generated code
//nolint
//
// Code generated by gen-go-spreadsheet. DO NOT EDIT.
package elements

import (
	"encoding/xml"
	"github.com/connerohnesorge/goffice/openxml"
	"github.com/connerohnesorge/goffice/openxml/types"
	"github.com/connerohnesorge/goffice/drawingml"
)

`
	// revive:enable:line-length-limit
	writeHeader(fElems, header)

	processSchemaFiles(fElems, schemasDir, files)
}

// processSchemaFiles iterates through schema files and triggers generation.
// It filters for SpreadsheetML and Excel schema files (including extensions).
func processSchemaFiles(
	f *os.File,
	schemasDir string,
	files []os.DirEntry,
) {
	for _, file := range files {
		name := file.Name()

		// Filter for Spreadsheet/Excel schemas (both main and extension)
		if !isSpreadsheetSchema(name) &&
			!isDrawingSchema(name) {
			continue
		}

		processSchemaFile(
			f,
			filepath.Join(schemasDir, name),
		)
	}
}

// processSchemaFile reads a single schema JSON and generates structs.
// It filters for complex types that are not enumerations.
func processSchemaFile(f *os.File, path string) {
	data, errRead := os.ReadFile(path)
	if errRead != nil {
		return
	}
	var schema SchemaFile
	if err := json.Unmarshal(data, &schema); err != nil {
		return
	}
	for i := range schema.Types {
		t := &schema.Types[i]
		t.TargetNamespace = schema.TargetNamespace
		if renamed, ok := renamedTypes[t.Name]; ok {
			t.ClassName = renamed
		}
		if len(t.Facets) == 0 &&
			t.ClassName != "" {
			generateStruct(f, t)
		}
	}
}

// writeHeader writes a standard header to a generated file.
// It logs an error to stderr if writing fails.
func writeHeader(f *os.File, header string) {
	if _, err := fmt.Fprint(f, header); err != nil {
		fmt.Fprintf(
			os.Stderr,
			"failed to write header: %v\n",
			err,
		)
	}
}

// safeFprintf wraps fmt.Fprintf to handle errors silently.
// It is used for code generation output to avoid cluttering logic.
func safeFprintf(
	f *os.File,
	format string,
	a ...any,
) {
	if _, err := fmt.Fprintf(f, format, a...); err != nil {
		fmt.Fprintf(
			os.Stderr,
			"failed to write to file: %v\n",
			err,
		)
	}
}
