package drawing

import (
	"fmt"
	"math"
	"strings"
)

// PathBuilder provides a fluent API for constructing PDF paths.
// It generates PDF content stream operators for path construction.
//
// PDF path construction uses the following operators:
//   - m (moveto): Start a new subpath at the given point
//   - l (lineto): Append a straight line to the current subpath
//   - c (curveto): Append a cubic Bezier curve
//   - v (curveto with first control point at current): Cubic Bezier variant
//   - y (curveto with second control point at endpoint): Cubic Bezier variant
//   - h (closepath): Close the current subpath
//   - re (rectangle): Append a rectangle as a complete subpath
//
// Path painting operators (not generated by PathBuilder):
//   - S (stroke): Stroke the path
//   - f (fill): Fill the path using non-zero winding
//   - f* (fill): Fill the path using even-odd rule
//   - B (fill and stroke): Fill and stroke the path
//   - n (no-op): End the path without painting
type PathBuilder struct {
	operators  strings.Builder
	currentX   float64
	currentY   float64
	startX     float64
	startY     float64
	hasStart   bool
	subpathLen int
}

// NewPathBuilder creates a new path builder.
func NewPathBuilder() *PathBuilder {
	return &PathBuilder{}
}

// MoveTo starts a new subpath at the specified point.
// This outputs the PDF 'm' operator.
func (p *PathBuilder) MoveTo(
	x, y float64,
) *PathBuilder {
	p.operators.WriteString(
		fmt.Sprintf(
			"%s %s m\n",
			formatFloat(x),
			formatFloat(y),
		),
	)
	p.currentX = x
	p.currentY = y
	p.startX = x
	p.startY = y
	p.hasStart = true
	p.subpathLen = 0

	return p
}

// LineTo appends a straight line from the current point to the specified point.
// This outputs the PDF 'l' operator.
func (p *PathBuilder) LineTo(
	x, y float64,
) *PathBuilder {
	if !p.hasStart {
		return p.MoveTo(x, y)
	}
	p.operators.WriteString(
		fmt.Sprintf(
			"%s %s l\n",
			formatFloat(x),
			formatFloat(y),
		),
	)
	p.currentX = x
	p.currentY = y
	p.subpathLen++

	return p
}

// CurveTo appends a cubic Bezier curve from the current point to (x3, y3),
// using (x1, y1) and (x2, y2) as control points.
// This outputs the PDF 'c' operator.
func (p *PathBuilder) CurveTo(
	x1, y1, x2, y2, x3, y3 float64,
) *PathBuilder {
	if !p.hasStart {
		p.MoveTo(p.currentX, p.currentY)
	}
	p.operators.WriteString(
		fmt.Sprintf("%s %s %s %s %s %s c\n",
			formatFloat(x1), formatFloat(y1),
			formatFloat(x2), formatFloat(y2),
			formatFloat(x3), formatFloat(y3)),
	)
	p.currentX = x3
	p.currentY = y3
	p.subpathLen++

	return p
}

// QuadraticCurveTo appends a quadratic Bezier curve from the current point to (x2, y2),
// using (x1, y1) as the control point.
// PDF doesn't support quadratic curves directly, so this converts to a cubic curve.
func (p *PathBuilder) QuadraticCurveTo(
	x1, y1, x2, y2 float64,
) *PathBuilder {
	if !p.hasStart {
		p.MoveTo(p.currentX, p.currentY)
	}
	// Convert quadratic to cubic Bezier
	// Control points for cubic are:
	// CP1 = P0 + 2/3 * (P1 - P0)
	// CP2 = P2 + 2/3 * (P1 - P2)
	cx1 := p.currentX + 2.0/3.0*(x1-p.currentX)
	cy1 := p.currentY + 2.0/3.0*(y1-p.currentY)
	cx2 := x2 + 2.0/3.0*(x1-x2)
	cy2 := y2 + 2.0/3.0*(y1-y2)

	return p.CurveTo(cx1, cy1, cx2, cy2, x2, y2)
}

// SmoothCurveTo appends a smooth cubic Bezier curve.
// The first control point is a reflection of the second control point
// of the previous curve.
func (p *PathBuilder) SmoothCurveTo(
	x2, y2, x3, y3 float64,
) *PathBuilder {
	// For a smooth curve, x1,y1 is the reflection of the previous control point
	// Since we don't track that, we use the current point
	return p.CurveTo(
		p.currentX,
		p.currentY,
		x2,
		y2,
		x3,
		y3,
	)
}

// ClosePath closes the current subpath by appending a straight line
// from the current point to the starting point of the subpath.
// This outputs the PDF 'h' operator.
func (p *PathBuilder) ClosePath() *PathBuilder {
	if p.hasStart {
		p.operators.WriteString("h\n")
		p.currentX = p.startX
		p.currentY = p.startY
	}

	return p
}

// Rectangle appends a rectangle as a complete subpath.
// The rectangle has its lower-left corner at (x, y) with the given width and height.
// This outputs the PDF 're' operator.
func (p *PathBuilder) Rectangle(
	x, y, width, height float64,
) *PathBuilder {
	p.operators.WriteString(
		fmt.Sprintf(
			"%s %s %s %s re\n",
			formatFloat(x),
			formatFloat(y),
			formatFloat(
				width,
			),
			formatFloat(height),
		),
	)
	p.currentX = x
	p.currentY = y
	p.startX = x
	p.startY = y
	p.hasStart = true
	p.subpathLen = 4

	return p
}

// RoundedRect appends a rounded rectangle path.
// The rectangle has its lower-left corner at (x, y) with the given dimensions.
// The radius specifies the corner radius.
func (p *PathBuilder) RoundedRect(
	x, y, width, height, radius float64,
) *PathBuilder {
	return p.RoundedRectVarying(
		x,
		y,
		width,
		height,
		radius,
		radius,
		radius,
		radius,
	)
}

// RoundedRectVarying appends a rounded rectangle with different radii for each corner.
// The radii are specified in order: top-left, top-right, bottom-right, bottom-left.
func (p *PathBuilder) RoundedRectVarying(
	x, y, width, height, tl, tr, br, bl float64,
) *PathBuilder {
	// Clamp radii to half of the smaller dimension
	maxRadius := math.Min(width, height) / 2
	tl = math.Min(tl, maxRadius)
	tr = math.Min(tr, maxRadius)
	br = math.Min(br, maxRadius)
	bl = math.Min(bl, maxRadius)

	// Magic number for approximating a quarter circle with a cubic Bezier
	// kappa = 4 * (sqrt(2) - 1) / 3
	const kappa = 0.5522847498

	// Start at bottom-left, after the bottom-left corner
	p.MoveTo(x+bl, y)

	// Bottom edge
	p.LineTo(x+width-br, y)

	// Bottom-right corner
	if br > 0 {
		p.CurveTo(
			x+width-br+br*kappa, y,
			x+width, y+br-br*kappa,
			x+width, y+br)
	}

	// Right edge
	p.LineTo(x+width, y+height-tr)

	// Top-right corner
	if tr > 0 {
		p.CurveTo(
			x+width, y+height-tr+tr*kappa,
			x+width-tr+tr*kappa, y+height,
			x+width-tr, y+height)
	}

	// Top edge
	p.LineTo(x+tl, y+height)

	// Top-left corner
	if tl > 0 {
		p.CurveTo(
			x+tl-tl*kappa, y+height,
			x, y+height-tl+tl*kappa,
			x, y+height-tl)
	}

	// Left edge
	p.LineTo(x, y+bl)

	// Bottom-left corner
	if bl > 0 {
		p.CurveTo(
			x, y+bl-bl*kappa,
			x+bl-bl*kappa, y,
			x+bl, y)
	}

	return p.ClosePath()
}

// Circle appends a circle path centered at (cx, cy) with the given radius.
func (p *PathBuilder) Circle(
	cx, cy, radius float64,
) *PathBuilder {
	return p.Ellipse(cx, cy, radius, radius)
}

// Ellipse appends an ellipse path centered at (cx, cy) with the given radii.
func (p *PathBuilder) Ellipse(
	cx, cy, rx, ry float64,
) *PathBuilder {
	// Approximate ellipse with 4 cubic Bezier curves
	// kappa = 4 * (sqrt(2) - 1) / 3
	const kappa = 0.5522847498

	// Control point offsets
	kx := rx * kappa
	ky := ry * kappa

	// Start at the right side
	p.MoveTo(cx+rx, cy)

	// Top-right quadrant
	p.CurveTo(
		cx+rx,
		cy+ky,
		cx+kx,
		cy+ry,
		cx,
		cy+ry,
	)

	// Top-left quadrant
	p.CurveTo(
		cx-kx,
		cy+ry,
		cx-rx,
		cy+ky,
		cx-rx,
		cy,
	)

	// Bottom-left quadrant
	p.CurveTo(
		cx-rx,
		cy-ky,
		cx-kx,
		cy-ry,
		cx,
		cy-ry,
	)

	// Bottom-right quadrant
	p.CurveTo(
		cx+kx,
		cy-ry,
		cx+rx,
		cy-ky,
		cx+rx,
		cy,
	)

	return p.ClosePath()
}

// Arc appends an arc path.
// The arc is drawn on a circle centered at (cx, cy) with the given radius,
// from startAngle to endAngle (in degrees).
// If clockwise is true, the arc is drawn clockwise; otherwise counter-clockwise.
func (p *PathBuilder) Arc(
	cx, cy, radius, startAngle, endAngle float64,
) *PathBuilder {
	return p.ArcTo(
		cx,
		cy,
		radius,
		radius,
		startAngle,
		endAngle,
		false,
	)
}

// ArcTo appends an arc path with separate x and y radii.
// The arc is drawn from startAngle to endAngle (in degrees).
// If largeArc is true and the arc spans less than 180 degrees, the larger arc is drawn.
func (p *PathBuilder) ArcTo(
	cx, cy, rx, ry, startAngle, endAngle float64,
	largeArc bool,
) *PathBuilder {
	// Convert angles to radians
	startRad := startAngle * math.Pi / 180
	endRad := endAngle * math.Pi / 180

	// Normalize angle difference
	diff := endRad - startRad
	for diff < 0 {
		diff += 2 * math.Pi
	}
	for diff > 2*math.Pi {
		diff -= 2 * math.Pi
	}

	// Handle large arc flag
	if largeArc && diff < math.Pi {
		diff = 2*math.Pi - diff
	}

	// Calculate start point
	startX := cx + rx*math.Cos(startRad)
	startY := cy + ry*math.Sin(startRad)

	// Move to start if not already there
	if !p.hasStart ||
		math.Abs(p.currentX-startX) > 0.001 ||
		math.Abs(p.currentY-startY) > 0.001 {
		p.MoveTo(startX, startY)
	}

	// Split arc into segments of at most 90 degrees
	const maxSegmentAngle = math.Pi / 2
	numSegments := int(
		math.Ceil(
			math.Abs(diff) / maxSegmentAngle,
		),
	)
	if numSegments < 1 {
		numSegments = 1
	}

	segmentAngle := diff / float64(numSegments)

	for i := range numSegments {
		angle1 := startRad + float64(
			i,
		)*segmentAngle
		angle2 := startRad + float64(
			i+1,
		)*segmentAngle
		p.arcSegment(
			cx,
			cy,
			rx,
			ry,
			angle1,
			angle2,
		)
	}

	return p
}

// arcSegment draws a single arc segment (max 90 degrees) using a cubic Bezier curve.
func (p *PathBuilder) arcSegment(
	cx, cy, rx, ry, startAngle, endAngle float64,
) {
	// Calculate the control point factor for this arc segment
	// Based on the formula: k = 4/3 * tan(angle/4)
	angle := endAngle - startAngle
	k := 4.0 / 3.0 * math.Tan(angle/4)

	// Start and end points
	x1 := cx + rx*math.Cos(startAngle)
	y1 := cy + ry*math.Sin(startAngle)
	x4 := cx + rx*math.Cos(endAngle)
	y4 := cy + ry*math.Sin(endAngle)

	// Control points
	x2 := x1 - k*rx*math.Sin(startAngle)
	y2 := y1 + k*ry*math.Cos(startAngle)
	x3 := x4 + k*rx*math.Sin(endAngle)
	y3 := y4 - k*ry*math.Cos(endAngle)

	p.CurveTo(x2, y2, x3, y3, x4, y4)
}

// Pie appends a pie (wedge) shape path.
// This is an arc with lines connecting to the center.
func (p *PathBuilder) Pie(
	cx, cy, radius, startAngle, endAngle float64,
) *PathBuilder {
	p.MoveTo(cx, cy)
	startRad := startAngle * math.Pi / 180
	p.LineTo(
		cx+radius*math.Cos(startRad),
		cy+radius*math.Sin(startRad),
	)
	p.Arc(cx, cy, radius, startAngle, endAngle)

	return p.ClosePath()
}

// Polygon appends a polygon path from a list of points.
// Points are specified as alternating x, y coordinates.
func (p *PathBuilder) Polygon(
	points ...float64,
) *PathBuilder {
	if len(points) < 4 {
		return p
	}
	p.MoveTo(points[0], points[1])
	for i := 2; i < len(points)-1; i += 2 {
		p.LineTo(points[i], points[i+1])
	}

	return p.ClosePath()
}

// Polyline appends a polyline path (open path through points).
// Points are specified as alternating x, y coordinates.
func (p *PathBuilder) Polyline(
	points ...float64,
) *PathBuilder {
	if len(points) < 4 {
		return p
	}
	p.MoveTo(points[0], points[1])
	for i := 2; i < len(points)-1; i += 2 {
		p.LineTo(points[i], points[i+1])
	}

	return p
}

// Star appends a star shape path.
// The star is centered at (cx, cy) with the given number of points.
// outerRadius is the radius to the points, innerRadius is the radius to the valleys.
// startAngle specifies the angle of the first point (in degrees, 0 = right).
func (p *PathBuilder) Star(
	cx, cy, outerRadius, innerRadius float64,
	points int,
	startAngle float64,
) *PathBuilder {
	if points < 3 {
		points = 5
	}

	angleStep := math.Pi / float64(points)
	startRad := startAngle * math.Pi / 180

	// Move to first outer point
	p.MoveTo(
		cx+outerRadius*math.Cos(startRad),
		cy+outerRadius*math.Sin(startRad))

	for i := range points {
		// Inner point
		innerAngle := startRad + float64(
			2*i+1,
		)*angleStep
		p.LineTo(
			cx+innerRadius*math.Cos(innerAngle),
			cy+innerRadius*math.Sin(innerAngle))

		// Outer point
		outerAngle := startRad + float64(
			2*i+2,
		)*angleStep
		p.LineTo(
			cx+outerRadius*math.Cos(outerAngle),
			cy+outerRadius*math.Sin(outerAngle))
	}

	return p.ClosePath()
}

// RegularPolygon appends a regular polygon path.
// The polygon is centered at (cx, cy) with the given number of sides and radius.
// startAngle specifies the angle of the first vertex (in degrees, 0 = right).
func (p *PathBuilder) RegularPolygon(
	cx, cy, radius float64,
	sides int,
	startAngle float64,
) *PathBuilder {
	if sides < 3 {
		sides = 3
	}

	angleStep := 2 * math.Pi / float64(sides)
	startRad := startAngle * math.Pi / 180

	// Move to first vertex
	p.MoveTo(
		cx+radius*math.Cos(startRad),
		cy+radius*math.Sin(startRad))

	for i := 1; i < sides; i++ {
		angle := startRad + float64(i)*angleStep
		p.LineTo(
			cx+radius*math.Cos(angle),
			cy+radius*math.Sin(angle))
	}

	return p.ClosePath()
}

// CurrentPoint returns the current point of the path.
func (p *PathBuilder) CurrentPoint() (x, y float64) {
	return p.currentX, p.currentY
}

// HasPath returns true if the path contains any path operations.
func (p *PathBuilder) HasPath() bool {
	return p.hasStart
}

// String returns the accumulated path operators as a string.
func (p *PathBuilder) String() string {
	return p.operators.String()
}

// Reset clears the path builder for reuse.
func (p *PathBuilder) Reset() *PathBuilder {
	p.operators.Reset()
	p.currentX = 0
	p.currentY = 0
	p.startX = 0
	p.startY = 0
	p.hasStart = false
	p.subpathLen = 0

	return p
}

// Stroke returns the path operators followed by the stroke operator.
func (p *PathBuilder) Stroke() string {
	return p.operators.String() + "S\n"
}

// Fill returns the path operators followed by the fill operator (non-zero winding).
func (p *PathBuilder) Fill() string {
	return p.operators.String() + "f\n"
}

// FillEvenOdd returns the path operators followed by the even-odd fill operator.
func (p *PathBuilder) FillEvenOdd() string {
	return p.operators.String() + "f*\n"
}

// FillAndStroke returns the path operators followed by fill and stroke.
func (p *PathBuilder) FillAndStroke() string {
	return p.operators.String() + "B\n"
}

// FillEvenOddAndStroke returns the path operators followed by even-odd fill and stroke.
func (p *PathBuilder) FillEvenOddAndStroke() string {
	return p.operators.String() + "B*\n"
}

// ClipNonZero returns the path operators followed by the clip operator (non-zero winding).
func (p *PathBuilder) ClipNonZero() string {
	return p.operators.String() + "W n\n"
}

// ClipEvenOdd returns the path operators followed by the even-odd clip operator.
func (p *PathBuilder) ClipEvenOdd() string {
	return p.operators.String() + "W* n\n"
}

// EndPath returns the path operators followed by the end path operator (no painting).
func (p *PathBuilder) EndPath() string {
	return p.operators.String() + "n\n"
}
